//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trening.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Busket
    {
        public int Id { get; set; }
        public Nullable<int> IdProd { get; set; }
        public Nullable<int> IdUser { get; set; }
        public Nullable<int> count { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual User User { get; set; }
    }
}
