//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trening.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductMaterial
    {
        public int IDProduct { get; set; }
        public int IDMaterial { get; set; }
        public Nullable<int> CountMaterial { get; set; }
    
        public virtual Material Material { get; set; }
        public virtual Product Product { get; set; }
    }
}
